[project]
name = "ocr"
version = "0.0.0"
description = "some basic ocr operations"
authors = [{ name = "Amir Kamali" }]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.0.0",
    "pytesseract>=0.3.13",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88
target-version = ["py314"]

[tool.hatch.build.targets.wheel]
# Explicitly tell Hatch which package(s) to include in the wheel.
# Your importable package is the top-level "ocr" package (folder with __init__.py).
packages = [
    { include = "ocr", from = "src" },
]

[dependency-groups]
dev = [
    "black>=25.9.0",
]
